/// Flutter icons CustomIcons
/// Copyright (C) 2022 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  CustomIcons
///      fonts:
///       - asset: fonts/CustomIcons.ttf
///
// ignore_for_file: constant_identifier_names

import 'package:flutter/widgets.dart';

class CustomIcons {
  CustomIcons._();

  static const _kFontFam = 'CustomIcons';
  static const String? _kFontPkg = null;

  static const IconData clarity_home_line = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData clarity_search_line = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData clarity_bell_outline_badged = IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData akar_icons_settings_horizontal3 = IconData(0xe808, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData akar_icons_plus = IconData(0xe809, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData bi_heart = IconData(0xe80a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData clarity_bookmark_line = IconData(0xe80b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData ei_comment = IconData(0xe80c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
